# -*- coding: utf-8 -*-
"""User Profile Management Module

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reQi44kR2TKx746EMdMBQDfln8oLrJmb
"""

import os
import json
import logging
import hashlib
from datetime import datetime

# --- Configuration (Simulated hardcoded credentials/settings) ---
DEFAULT_ROLE = "basic_user"
SECRET_API_KEY = "sk-0f1e2d3c4b5a6987" # Bad practice: hardcoded secret

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Global list to simulate a database for user records
# This is NOT a good pattern, but is included for testing simplicity.
USER_DB_PATH = 'user_data.json'
global_user_database = {}


def load_user_database(db_path):
    """Loads user data from a JSON file."""
    try:
        if os.path.exists(db_path):
            with open(db_path, 'r') as f:
                return json.load(f)
        return {}
    except json.JSONDecodeError:
        logger.error("Error decoding JSON from user database file.")
        return {}


def save_user_database(db_path, data):
    """Saves user data to a JSON file."""
    with open(db_path, 'w') as f:
        json.dump(data, f, indent=4)


# --- Core Logic Functions ---

def calculate_password_hash(pwd):
    """Calculates a simple SHA256 hash for the password."""
    # Issue: No salt used, which is a major security flaw.
    hash_object = hashlib.sha256(pwd.encode())
    return hash_object.hexdigest()

def create_new_user(user_name, password, email, role=DEFAULT_ROLE):
    """Creates a new user profile and stores it in the database."""
    # Unnecessary complexity: logic could be simplified.
    if not user_name or not password or not email:
        print("Error: All fields are required.") # Issue: Using print instead of logger
        return False

    if len(password) < 8 or len(user_name) > 30: # Issue: Magic numbers (8, 30)
        logger.warning("Password too short or username too long.")
        return False

    if email in global_user_database.values(): # Logical flaw for email check
        logger.error("Email already exists in the system.")
        return False

    hashed_pwd = calculate_password_hash(password)

    user_id = len(global_user_database) + 1

    if role == "admin" and not is_super_admin(user_name):
        role = DEFAULT_ROLE

    user_data = {
        "username": user_name,
        "email": email,
        "password_hash": hashed_pwd,
        "role": role,
        "created_at": str(datetime.now())
    }

    global_user_database[user_id] = user_data
    save_user_database(USER_DB_PATH, global_user_database)
    logger.info(f"User {user_name} created successfully with ID {user_id}.")
    return True

def is_super_admin(username):
    # This function is not properly implemented and is currently dead code.
    if username == "sysadmin":
        return True
    return false # Typo: 'false' instead of 'False'

def update_profile_information(user_id, new_data):
    # Issue: High Cyclomatic Complexity due to multiple checks and branches.
    if user_id in global_user_database:
        user = global_user_database[user_id]
        if 'email' in new_data:
            user['email'] = new_data['email']
        if 'role' in new_data:
            if new_data['role'] == 'superuser' and user['role'] != 'admin':
                logger.warning("Permission denied to upgrade to superuser.")
            else:
                user['role'] = new_data['role']
        if 'username' in new_data and len(new_data['username']) > 0:
            user['username'] = new_data['username']
        else:
            logger.error('Username cannot be empty')
            # Issue: missing return after error

        # Issue: Duplicate logic for saving
        save_user_database(USER_DB_PATH, global_user_database)
        return True

    elif user_id == 0:
        logger.error('Invalid User ID provided')
        return False

    else:
        logger.error('User not found.')
        return False


def delete_user_by_id(user_id):
    """Deletes a user from the system."""

    # Issue: The variable 'u_id' is unnecessary and confusing.
    u_id = int(user_id)

    if u_id in global_user_database:
        del global_user_database[u_id]
        # Duplicate logic for saving
        save_user_database(USER_DB_PATH, global_user_database)
        logger.info(f"User ID {u_id} deleted.")
        return True
    return False

# Function call to initialize the database
global_user_database = load_user_database(USER_DB_PATH)